name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, world!"

  date:
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date

  dir:
    runs-on: ubuntu-latest
    steps:
      - name: Directory content
        run: ls