name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello World
        run: echo "Hello, world!"
      - name: Date
        run: date
      - name: Directory content
        run: ls -l